from typing import Dict

blocks = [
    {'id':0, 'name':'Fire generator', 'default': True, 'category': 'Machine', 'challenge':''},
    {'id':1, 'name':'Water generator', 'default': True, 'category': 'Machine', 'challenge':''},
    {'id':2, 'name':'Earth generator', 'default': True, 'category': 'Machine', 'challenge':''},
    {'id':3, 'name':'Air generator', 'default': True, 'category': 'Machine', 'challenge':''},
    {'id':4, 'name':'Combiner', 'default': True, 'category': 'Machine', 'challenge':''},
    {'id':5, 'name':'Disassembler', 'default': True, 'category': 'Machine', 'challenge':''},
    {'id':6, 'name':'Wall', 'default': True, 'category': 'Machine', 'challenge':''},
    {'id':7, 'name':'Conveyor', 'default': True, 'category': 'Machine', 'challenge':''},

    {'id':11, 'name':'Fire', 'default': True, 'category': 'Raw element', 'challenge':'Fakutori.BlockChallenges.MakeCopiesOfBlock'},
    {'id':14, 'name':'Water', 'default': True, 'category': 'Raw element', 'challenge':'Fakutori.BlockChallenges.MakeCopiesOfBlock'},
    {'id':15, 'name':'Earth', 'default': True, 'category': 'Raw element', 'challenge':'Fakutori.BlockChallenges.MakeCopiesOfBlock'},
    {'id':16, 'name':'Air', 'default': True, 'category': 'Raw element', 'challenge':'Fakutori.BlockChallenges.MakeCopiesOfBlock'},

    {'id':8, 'name':'Toggle conveyor', 'default': False, 'category': 'Machine', 'challenge':''},
    {'id':9, 'name':'Cross conveyor', 'default': False, 'category': 'Machine', 'challenge':''},
    {'id':10, 'name':'Pusher', 'default': False, 'category': 'Machine', 'challenge':''},
    {'id':12, 'name':'Yellow fire', 'default': False, 'category': 'Energy', 'challenge':'Fakutori.BlockChallenges.BurnBlocks'},
    {'id':13, 'name':'Blue fire', 'default': False, 'category': 'Energy', 'challenge':'Fakutori.BlockChallenges.BurnBlocks'},
    {'id':17, 'name':'Wood', 'default': False, 'category': 'Organic', 'challenge':'Fakutori.BlockChallenges.GetBurnedByBlock'},
    {'id':18, 'name':'Coal', 'default': False, 'category': 'Organic', 'challenge':'Fakutori.BlockChallenges.UseInCombiner'},
    {'id':19, 'name':'Oil', 'default': False, 'category': 'Organic', 'challenge':'Fakutori.BlockChallenges.GetBurnedByBlock'},
    {'id':20, 'name':'Smoke', 'default': False, 'category': 'Misc elements', 'challenge':'Fakutori.BlockChallenges.TransformBlock'},
    {'id':21, 'name':'Lava', 'default': False, 'category': 'Mineral', 'challenge':'Fakutori.BlockChallenges.BurnBlocks'},
    {'id':22, 'name':'Dust', 'default': False, 'category': 'Mineral', 'challenge':'Fakutori.BlockChallenges.MakeShiny'},
    {'id':23, 'name':'Stone', 'default': False, 'category': 'Mineral', 'challenge':'Fakutori.BlockChallenges.TransformBlock'},
    {'id':24, 'name':'Sand', 'default': False, 'category': 'Mineral', 'challenge':'Fakutori.BlockChallenges.MakeCopiesOfBlock'},
    {'id':25, 'name':'Meteorite', 'default': False, 'category': 'Mineral', 'challenge':'Fakutori.BlockChallenges.UseInCombiner'},
    {'id':26, 'name':'Ether', 'default': False, 'category': 'Misc elements', 'challenge':'Fakutori.BlockChallenges.UseInCombiner'},
    {'id':27, 'name':'Shooting star', 'default': False, 'category': 'Misc elements', 'challenge':'Fakutori.BlockChallenges.MakeShiny'},
    {'id':28, 'name':'Steam', 'default': False, 'category': 'Energy', 'challenge':'Fakutori.BlockChallenges.TransformBlock'},
    {'id':29, 'name':'Copper', 'default': False, 'category': 'Metal', 'challenge':'Fakutori.BlockChallenges.GetDissolvedByBlock'},
    {'id':30, 'name':'Iron', 'default': False, 'category': 'Metal', 'challenge':'Fakutori.BlockChallenges.GetDissolvedByBlock'},
    {'id':31, 'name':'Silver', 'default': False, 'category': 'Metal', 'challenge':'Fakutori.BlockChallenges.TransformBlock'},
    {'id':32, 'name':'Gold', 'default': False, 'category': 'Metal', 'challenge':'Fakutori.BlockChallenges.SellValueOfBlocks'},
    {'id':33, 'name':'Ruby', 'default': False, 'category': 'Mineral', 'challenge':'Fakutori.BlockChallenges.GenerateMoneyFromInventory'},
    {'id':34, 'name':'Luck', 'default': False, 'category': 'Concept', 'challenge':'Fakutori.BlockChallenges.UseInCombiner'},
    {'id':35, 'name':'Magic', 'default': False, 'category': 'Concept', 'challenge':'Fakutori.BlockChallenges.MakeWithIngredientSets'},
    {'id':36, 'name':'Time', 'default': False, 'category': 'Concept', 'challenge':'Fakutori.BlockChallenges.UseInCombiner'},
    {'id':37, 'name':'Entropy', 'default': False, 'category': 'Concept', 'challenge':'Fakutori.BlockChallenges.MakeWithIngredientSets'},
    {'id':38, 'name':'Void', 'default': False, 'category': 'Concept', 'challenge':'Fakutori.BlockChallenges.MakeCopiesOfBlock'},
    {'id':39, 'name':'Fizzy water', 'default': False, 'category': 'Misc elements', 'challenge':'Fakutori.BlockChallenges.SellValueOfBlocks'},
    {'id':40, 'name':'Acid', 'default': False, 'category': 'Misc elements', 'challenge':'Fakutori.BlockChallenges.DissolveBlocks'},
    {'id':41, 'name':'Plasma', 'default': False, 'category': 'Energy', 'challenge':'Fakutori.BlockChallenges.MakeCopiesOfBlock'},
    {'id':42, 'name':'Electricity', 'default': False, 'category': 'Energy', 'challenge':'Fakutori.BlockChallenges.ApplyStatusToBlocks'},
    {'id':43, 'name':'Quicksilver', 'default': False, 'category': 'Metal', 'challenge':'Fakutori.BlockChallenges.SellValueOfBlocks'},
    {'id':44, 'name':'Light', 'default': False, 'category': 'Magical', 'challenge':'Fakutori.BlockChallenges.MakeWithIngredientSets'},
    {'id':45, 'name':'Darkness', 'default': False, 'category': 'Magical', 'challenge':'Fakutori.BlockChallenges.MakeWithIngredientSets'},
    {'id':46, 'name':'Antimatter', 'default': False, 'category': 'Energy', 'challenge':'Fakutori.BlockChallenges.TurnValueIntoVoid'},
    {'id':47, 'name':'Quartz', 'default': False, 'category': 'Mineral', 'challenge':'Fakutori.BlockChallenges.MakeAllColorVariants'},
    {'id':48, 'name':'Rainbow', 'default': False, 'category': 'Magical', 'challenge':'Fakutori.BlockChallenges.MakeWithIngredientSets'},
    {'id':49, 'name':'Black hole', 'default': False, 'category': 'Unique', 'challenge':'Fakutori.BlockChallenges.AbsorbBlocks'},
    {'id':50, 'name':'Quasar', 'default': False, 'category': 'Legendary', 'challenge':'Fakutori.BlockChallenges.TeleportBlocks'},
    {'id':51, 'name':'Quartz black', 'default': False, 'category': 'Mineral', 'challenge':''},
    {'id':52, 'name':'Quartz blue', 'default': False, 'category': 'Mineral', 'challenge':''},
    {'id':53, 'name':'Quartz brown', 'default': False, 'category': 'Mineral', 'challenge':''},
    {'id':54, 'name':'Quartz green', 'default': False, 'category': 'Mineral', 'challenge':''},
    {'id':55, 'name':'Quartz grey', 'default': False, 'category': 'Mineral', 'challenge':''},
    {'id':56, 'name':'Quartz orange', 'default': False, 'category': 'Mineral', 'challenge':''},
    {'id':57, 'name':'Quartz pink', 'default': False, 'category': 'Mineral', 'challenge':''},
    {'id':58, 'name':'Quartz purple', 'default': False, 'category': 'Mineral', 'challenge':''},
    {'id':59, 'name':'Quartz red', 'default': False, 'category': 'Mineral', 'challenge':''},
    {'id':60, 'name':'Quartz white', 'default': False, 'category': 'Mineral', 'challenge':''},
    {'id':61, 'name':'Quartz yellow', 'default': False, 'category': 'Mineral', 'challenge':''},
    {'id':63, 'name':'Puller', 'default': False, 'category': 'Machine', 'challenge':''}
]

colors = [
    'Orange',
    'Blue',
    'Brown',
    'White',
    'Black',
    'Yellow',
    'Pink',
    'Grey',
    'Green',
    'Red',
    'Purple',
]