name: Release APWorld

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '~3.12'
          check-latest: true

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build APWorld
        run: python Launcher.py "Build APWorlds" -- "Fakutori"

      - name: Release
        uses: softprops/action-gh-release@975c1b265e11dd76618af1c374e7981f9a6ff44a
        with:
          name: Fakutori ${{ github.ref_name }}
          files: build/apworlds/fakutori.apworld
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
